apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.8
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:670e63e6d4a89151b2ae0290612cb4df8dcf6d8ee20037df0efc78a15fc690eb
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
