apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.3.0
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:e419aefcaa8718e64197a28063100eefa65bb93c4d29a7b500c5946ca98ba598
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
