apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp-common-services-1.15.3
  publisher: IBM
  image: icr.io/cpopen/ibm-common-service-catalog@sha256:c8d461f5d9f933cbae94e84dd28643f0874a58a04d56de23181610c65c473314
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
