apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-asset-repository-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-asset-repository-1.5.7-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-asset-repository-catalog@sha256:6de14c5e0d90f07815f30c9864f7c37fa539a61968e24a8bd309e23e1899a7dd
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
