apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-platform-navigator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-platform-navigator-1.7.1
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-platform-navigator-catalog@sha256:40c2ba2325d3c24e1e32c36490c5b5a7b0945c894f95dfd7c6fae14390214ab2
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
