apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.3.1
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:725ad3fd33a712df16aca9f21181c13fdcff7fc6dab50d9278f765e106ec327e
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
