apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-asset-repository-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-asset-repository-1.5.3-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-asset-repository-catalog@sha256:ce2e403890c78e3ef20ac31cb4774774705960ffa744fdac6d8a8566e83516d9
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
