apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: appconnect-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-appconnect-6.1.1
  publisher: IBM
  image: icr.io/cpopen/appconnect-operator-catalog@sha256:bf022b4ea8089705b52af3dae7f49aa10c869c44b4e5fea535434dd17638e9f8
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
