apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: aspera-operators
  namespace: openshift-marketplace
spec:
  displayName: ibm-aspera-hsts-operator-1.5.2
  publisher: IBM
  image: icr.io/cpopen/aspera-hsts-catalog@sha256:65708f2daa843ca577a26f0dd9660f416d852bda951a7d740af30bf2fc53b5b8
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
