apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.2.1
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:c28c163afa3f727283baec9c665964808daac7239bf94d48cfde370d6fe75907
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
