apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.3.2
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:cf3c9e4dc209e696405357bd16f5dcfec3c6ad77d812152f8b648f59e5bc14a5
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
