apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-platform-navigator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-platform-navigator-7.0.1
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-platform-navigator-catalog@sha256:bd4b56e480da0b72649547d6af46cf41caf143cf010cd9ac221d6af18dd83f9b
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
