apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.2
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:d76496b571eb6380910a59fca7aef53aa3d9c7ef5ea1b5dfcaabaf08b1ddce7e
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
