apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: appconnect-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-appconnect-8.0.0
  publisher: IBM
  image: icr.io/cpopen/appconnect-operator-catalog@sha256:8cda29d2dedc0a6943e7416fc8b5b7020e6d5b5adf29dd557126b7dae96203ba
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
