apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.0
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:f658de5cfcc72090d9e313a01ff310a9a291f17988592da44a47ac23b3d9107f
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
