apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.6
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:ad577f8b62d75825b180f5af3f2262a576bec617fb96ea42f9167d28a7a5014a
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
