apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: appconnect-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-appconnect-5.1.0
  publisher: IBM
  image: icr.io/cpopen/appconnect-operator-catalog@sha256:cdd951b0c84005fc37bb4193212ee35da55af620287646f95565c78d800946cf
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
