apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.2.0
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:512739b3b994a636d4b965ef288993871e9e47fe82eb17e2964551193030eddf
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
