apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-platform-navigator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-platform-navigator-7.0.4
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-platform-navigator-catalog@sha256:77f4ae2b653ad7c3745f6504de3e5ace33c53e9466c52c5a3a32c8bbc91d66e3
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
