apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: appconnect-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-appconnect-5.0.1
  publisher: IBM
  image: icr.io/cpopen/appconnect-operator-catalog@sha256:68ef2e2d3702e659176d76c9324cbc348a73e552d7b8d1366192ffff8e5eb27d
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
