apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-platform-navigator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-platform-navigator-1.7.6
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-platform-navigator-catalog@sha256:19ffc0ccfce9f0d8ea8784f9eba5606960e0a59d21bfc89342bcfb2ed580094c
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
