apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-datapower-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-datapower-operator-1.6.2-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/datapower-operator-catalog@sha256:e53f031d3dc118a5cb94f727ee45c6b6487f6073fb288066eb4672e4bf79f02c
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
