apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-asset-repository-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-asset-repository-1.5.5-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-asset-repository-catalog@sha256:ddb3e7d25c11cb80003f03867d64293f2062828bb06ed8a356fdf0970c517140
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
