apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.9
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:8b2140b09b60ffd59c689605eb0bc00bcdd273578b70b6b3410e7463cbd615be
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
