apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-asset-repository-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-asset-repository-1.5.8-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-asset-repository-catalog@sha256:754f7e2f25b96479b737385c6e77058a406c5eef56c6b2cb3ace91c06a6e7588
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
