apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.3
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:c4c0f487198df9b9af9e6182f80ba4c5bf0b92858a65f174b441f8343373c30a
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
