apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-platform-navigator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-platform-navigator-1.7.2
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-platform-navigator-catalog@sha256:bab0d1785392785a8f6b09d3d3779641ba9be461b8a89c755ab93ccd369d128d
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
