apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-asset-repository-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-asset-repository-1.5.1-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-asset-repository-catalog@sha256:010eaf61350b8b265e7010f8261a8aaed87cda87b769b27e234fd81892258b17
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
