apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-asset-repository-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-asset-repository-1.5.6-linux-amd64
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-asset-repository-catalog@sha256:28377a5d5d29987a4bf452d5a276222637f9219449c7785fcb1634120144dbec
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
