apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-integration-platform-navigator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-integration-platform-navigator-1.7.9
  publisher: IBM
  image: icr.io/cpopen/ibm-integration-platform-navigator-catalog@sha256:ba2fd7d37af337a10b53b0b82268e4c28ff9f49a17bba5d8e8c6ec6896d69dad
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
