apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: appconnect-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-appconnect-6.2.0
  publisher: IBM
  image: icr.io/cpopen/appconnect-operator-catalog@sha256:70e3e51948079d5630b8dcaf0981d9b50cd21ae1eacabf16125f5c48f45bae25
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
