apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.2.2
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:df3e524b283e14b4815f2c8252382e8991689bd2afd52da6b89d38e0cd9a4b60
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
