apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.5
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:546cf3b86b77a7c655a81d3241aefe619f8a044e174fe438c219f06f1e2e90c1
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
