apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.4
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:b8d5a1837ac8ec43a5ae1d5544767507324584bafa7a2009f09030695c0f6a99
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
