apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.10
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:5df28821892aa7bcd8056fab8e6a805ab91bd7175ddd1c4064c6b0be1bf67c95
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
