apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibmmq-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: ibm-mq-2.0.7
  publisher: IBM
  image: icr.io/cpopen/ibm-mq-operator-catalog@sha256:13ddfd679f8ca9356e4c47b4df65f9d50cad822b6110976d71b9b0c850a51a09
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
